repos:
    ast:
        git: /Users/xdanger/Sites/xdcdn.net/uri-ast.git
    ktk:
        git: /Users/xdanger/Sites/xdcdn.net/uri-ktk.git
    sgf:
        git: /Users/xdanger/Sites/xdcdn.net/uri-sgf.git
    sgd:
        git: /Users/xdanger/Sites/xdcdn.net/uri-sgd.git
    jsk:
        git: /Users/xdanger/Sites/xdcdn.net/uri-jsk.git
    sxd:
        git: /Users/xdanger/Sites/xdcdn.net/uri-sxd.git
    xxd:
        git: /Users/xdanger/Sites/xdcdn.net/uri-xxd.git
    syk:
        git: /Users/xdanger/Sites/xdcdn.net/uri-syk.git
redis:
    host: 127.0.0.1
    port: 6379
    base: 2
